/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiCreateMomentRouteImport } from './routes/api/create-moment'

const ApiCreateMomentRoute = ApiCreateMomentRouteImport.update({
  id: '/api/create-moment',
  path: '/api/create-moment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/create-moment': typeof ApiCreateMomentRoute
}
export interface FileRoutesByTo {
  '/api/create-moment': typeof ApiCreateMomentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/create-moment': typeof ApiCreateMomentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/create-moment'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/create-moment'
  id: '__root__' | '/api/create-moment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiCreateMomentRoute: typeof ApiCreateMomentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/create-moment': {
      id: '/api/create-moment'
      path: '/api/create-moment'
      fullPath: '/api/create-moment'
      preLoaderRoute: typeof ApiCreateMomentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiCreateMomentRoute: ApiCreateMomentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
