/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VV3RouteImport } from './routes/v.v3'
import { Route as VNextRouteImport } from './routes/v.next'
import { Route as VBeta2RouteImport } from './routes/v.beta2'
import { Route as VBeta1RouteImport } from './routes/v.beta1'
import { Route as MIdRouteImport } from './routes/m.$id'
import { Route as ApiCreateMomentRouteImport } from './routes/api/create-moment'
import { Route as V3MIdRouteImport } from './routes/v3.m.$id'
import { Route as V2MIdRouteImport } from './routes/v2.m.$id'

const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VV3Route = VV3RouteImport.update({
  id: '/v/v3',
  path: '/v/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const VNextRoute = VNextRouteImport.update({
  id: '/v/next',
  path: '/v/next',
  getParentRoute: () => rootRouteImport,
} as any)
const VBeta2Route = VBeta2RouteImport.update({
  id: '/v/beta2',
  path: '/v/beta2',
  getParentRoute: () => rootRouteImport,
} as any)
const VBeta1Route = VBeta1RouteImport.update({
  id: '/v/beta1',
  path: '/v/beta1',
  getParentRoute: () => rootRouteImport,
} as any)
const MIdRoute = MIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateMomentRoute = ApiCreateMomentRouteImport.update({
  id: '/api/create-moment',
  path: '/api/create-moment',
  getParentRoute: () => rootRouteImport,
} as any)
const V3MIdRoute = V3MIdRouteImport.update({
  id: '/v3/m/$id',
  path: '/v3/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V2MIdRoute = V2MIdRouteImport.update({
  id: '/v2/m/$id',
  path: '/v2/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/api/create-moment': typeof ApiCreateMomentRoute
  '/m/$id': typeof MIdRoute
  '/v/beta1': typeof VBeta1Route
  '/v/beta2': typeof VBeta2Route
  '/v/next': typeof VNextRoute
  '/v/v3': typeof VV3Route
  '/v2/m/$id': typeof V2MIdRoute
  '/v3/m/$id': typeof V3MIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/api/create-moment': typeof ApiCreateMomentRoute
  '/m/$id': typeof MIdRoute
  '/v/beta1': typeof VBeta1Route
  '/v/beta2': typeof VBeta2Route
  '/v/next': typeof VNextRoute
  '/v/v3': typeof VV3Route
  '/v2/m/$id': typeof V2MIdRoute
  '/v3/m/$id': typeof V3MIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/api/create-moment': typeof ApiCreateMomentRoute
  '/m/$id': typeof MIdRoute
  '/v/beta1': typeof VBeta1Route
  '/v/beta2': typeof VBeta2Route
  '/v/next': typeof VNextRoute
  '/v/v3': typeof VV3Route
  '/v2/m/$id': typeof V2MIdRoute
  '/v3/m/$id': typeof V3MIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/api/create-moment'
    | '/m/$id'
    | '/v/beta1'
    | '/v/beta2'
    | '/v/next'
    | '/v/v3'
    | '/v2/m/$id'
    | '/v3/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/api/create-moment'
    | '/m/$id'
    | '/v/beta1'
    | '/v/beta2'
    | '/v/next'
    | '/v/v3'
    | '/v2/m/$id'
    | '/v3/m/$id'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/api/create-moment'
    | '/m/$id'
    | '/v/beta1'
    | '/v/beta2'
    | '/v/next'
    | '/v/v3'
    | '/v2/m/$id'
    | '/v3/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  ApiCreateMomentRoute: typeof ApiCreateMomentRoute
  MIdRoute: typeof MIdRoute
  VBeta1Route: typeof VBeta1Route
  VBeta2Route: typeof VBeta2Route
  VNextRoute: typeof VNextRoute
  VV3Route: typeof VV3Route
  V2MIdRoute: typeof V2MIdRoute
  V3MIdRoute: typeof V3MIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/v3': {
      id: '/v/v3'
      path: '/v/v3'
      fullPath: '/v/v3'
      preLoaderRoute: typeof VV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/next': {
      id: '/v/next'
      path: '/v/next'
      fullPath: '/v/next'
      preLoaderRoute: typeof VNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/beta2': {
      id: '/v/beta2'
      path: '/v/beta2'
      fullPath: '/v/beta2'
      preLoaderRoute: typeof VBeta2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/beta1': {
      id: '/v/beta1'
      path: '/v/beta1'
      fullPath: '/v/beta1'
      preLoaderRoute: typeof VBeta1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$id': {
      id: '/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-moment': {
      id: '/api/create-moment'
      path: '/api/create-moment'
      fullPath: '/api/create-moment'
      preLoaderRoute: typeof ApiCreateMomentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/m/$id': {
      id: '/v3/m/$id'
      path: '/v3/m/$id'
      fullPath: '/v3/m/$id'
      preLoaderRoute: typeof V3MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/m/$id': {
      id: '/v2/m/$id'
      path: '/v2/m/$id'
      fullPath: '/v2/m/$id'
      preLoaderRoute: typeof V2MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  ApiCreateMomentRoute: ApiCreateMomentRoute,
  MIdRoute: MIdRoute,
  VBeta1Route: VBeta1Route,
  VBeta2Route: VBeta2Route,
  VNextRoute: VNextRoute,
  VV3Route: VV3Route,
  V2MIdRoute: V2MIdRoute,
  V3MIdRoute: V3MIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
